### ISSUE TITLE
Ubuntu 24.04

### ISSUE THREAD

**Issue by janiosarmento** [WordOps/WordOps#638]
Hi,

Ubuntu 24.04 was just released.

Do we have any prospects about WO being compatible with it?

Thanks!

**Comment by janiosarmento** [comment]
JFYI, I tried installing WordOps with `--force` and got:

```
Collecting pynginxconfig (from wordops)
  Using cached pynginxconfig-0.3.4.tar.gz (3.4 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [11 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 14, in <module>
        File "/opt/wo/lib/python3.12/site-packages/setuptools/__init__.py", line 16, in <module>
          import setuptools.version
        File "/opt/wo/lib/python3.12/site-packages/setuptools/version.py", line 1, in <module>
          import pkg_resources
        File "/opt/wo/lib/python3.12/site-packages/pkg_resources/__init__.py", line 2158, in <module>
          register_finder(pkgutil.ImpImporter, find_on_path)
                          ^^^^^^^^^^^^^^^^^^^
      AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?
      [end of output]
  ```

**Comment by VirtuBox** [comment]
Hello @janiosarmento;
yes I'm working on it. Nginx package is already available, but I haven't checked WordOps install script yet.

**Comment by VirtuBox** [comment]
I'm still waiting for all php packages to be available on Ubuntu 24.04 LTS.

**Comment by VirtuBox** [comment]
Everything is working on Ubuntu 24.04 LTS excepted `--php` stack because there are still missing packages.
I'm still working on HTTP/3 configuration.

**Comment by janiosarmento** [comment]
> I'm still working on HTTP/3 configuration.

Are you going to update your Nginx-EE script, that one which compiles a custom Nginx?

**Comment by VirtuBox** [comment]
> > I'm still working on HTTP/3 configuration.
> 
> Are you going to update your Nginx-EE script, that one which compiles a custom Nginx?

Yes, I have updated it for Ubuntu 24.04 LTS

**Comment by TimRyanKaslovia** [comment]
Installation fails
Reading package lists... Done
W: http://mariadb.mirrors.ovh.net/MariaDB/repo/10.11/ubuntu/dists/noble/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.
W: https://ppa.launchpadcontent.net/git-core/ppa/ubuntu/dists/noble/InRelease: Signature by key E1DD270288B4E6030699E45FA1715D88E1DF1F24 uses weak algorithm (rsa1024)
W: https://ppa.launchpadcontent.net/ondrej/php/ubuntu/dists/noble/InRelease: Signature by key 14AA40EC0831756756D7F66C4F4EA0AAE5267A6C uses weak algorithm (rsa1024)

The MariaDB repo is out of date and the PHP repo is 8.2 not 8.3

**Comment by janiosarmento** [comment]
> Installation fails

Thanks for confirming what the entire issue is saying: WO is not ready for Ubuntu 24.04 yet because not all necessary packages have been ported or updated. :)

**Comment by TimRyanKaslovia** [comment]
This is not just an issue of one outdated package, I encountered a number of outdates some that could be worked around and others that made the “engine” fail. Is it worth a detailed report?

 

The platform I use is a ProxMox PVE 8.2.2 Cluster built on Debian Bookworm hosting 60 or so Ubuntu 24.04 Server VM’s. For the record they are approximately 15 to 20% faster than 22.04 LTS on the same hardware and QEMU  platform

**Comment by janiosarmento** [comment]
All issues are known and depend on third parties to be resolved. I, for instance, reported them on the first day after Ubuntu 24 was released.

If you asked me for an opinion, you'd better wait for the next release, as we all are waiting.

If the next release is announced as officially supporting Ubuntu 24, and you encounter issues, then a detailed report might help - but now it would add more noise to the communication.

My two cents, only.

**Comment by TimRyanKaslovia** [comment]
Thanks for the insider info, I well wait for the presumably imminent release

**Comment by VirtuBox** [comment]
PHP packages are going to be available in the next few days.

**Comment by VirtuBox** [comment]
Ubuntu 24.04 LTS support is available 😊

https://github.com/WordOps/WordOps/releases/tag/v3.21.3
